### ISSUE TITLE
TypeError: sync() got an unexpected keyword argument 'resource_types'

### ISSUE THREAD

**Issue by markwk** [zandrmartin/todoist-completed-tasks-csv#1]
When I run $ python3 todoist-csv.py <API-KEY> test.csv I am getting an error: 

```
Traceback (most recent call last):
  File "todoist-csv.py", line 88, in <module>
    sync = api.sync(resource_types=['all'])
TypeError: sync() got an unexpected keyword argument 'resource_types'
```

Followed the instructions and I believe I got everything setup correctly.

**Comment by zandrmartin** [comment]
The Todoist API has changed several times since I originally wrote this. I have no current plans to further develop this project (nor would I even be able to - I no longer have access to a paid Todoist account). PRs are welcome though.
